DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

blog/urls.py
from django.conf.urls import url

from .import views

app_name = 'blog'
urlpatterns = [
    #类
    url(r'^$',views.index,name='index'),#首页函数
    url(r'^post/(?P<pk>[0-9]+)/$',views.PostDetaiIView.as_view(),name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$',views.CategoryView.as_view(),name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    #函数
    # url(r'^$',views.IndexView.as_view(),name='index'),
    # url(r'^search/$',views.search,name='search'),
    # url(r'category/(?P<pk>[0-9]+)/$',views.category,name='category'),
    # url(r'^post/(?P<pk>[0-9]+)/$',views.detail,name='detail'),
    # url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
]

blog_project/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog.feeds import AllPostRssFeed
import xadmin
import  ditor

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),

    #url(r'^admin/', admin.site.urls),

    url(r'',include('blog.urls')),
    url(r'',include('comments.urls')),
    url(r'^all/rss/$',AllPostRssFeed(),name='rss'),
    url(r'^search/', include('haystack.urls')),
    url(r'^ueditor/', include('ditor.urls'))
]
from django.conf import settings
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/urls.py
from  django.conf.urls import url


from .import views

app_name = 'comments'
urlpatterns = [
    # url(r'^comment/post/(?P<post_pk>[0-9]+)/$',views.post_comment,name='post_comment'),
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

ditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

blog/models.py
from django.db import models
from  django.contrib.auth.models import User
from django.utils.six import python_2_unicode_compatible
from django.urls import reverse
import  markdown
from django.utils.html import strip_tags

from ditor.models import UEditorField
# Create your models here.


@python_2_unicode_compatible
class Category(models.Model):
    """分类"""
    name = models.CharField(max_length=100,verbose_name='分类')

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Tag(models.Model):
    """标签Tag"""
    name = models.CharField(max_length=100,verbose_name='标签')


    def __str__(self):
        return self.name

@python_2_unicode_compatible
class Post(models.Model):
    """文章"""
    STATUS_CHOICES = (
        ('draft','草稿'),
        ('published','已发布'),
        )
    title = models.CharField(max_length=70,verbose_name='文章标题')
    body = UEditorField('内容', height=300, width=800,max_length=1024000000000,
                           default=u'', blank=True, imagePath="images/",
                           toolbars='besttome', filePath='files/')
    create_time = models.DateTimeField(verbose_name='文章创建时间')
    modified_time = models.DateTimeField(verbose_name='文章最后修改时间')
    excerpt = models.CharField(max_length=200,blank=True,verbose_name='文章摘要')
    category = models.ForeignKey(Category,verbose_name='分类')
    tags = models.ManyToManyField(Tag,blank=True,verbose_name='标签')
    author = models.ForeignKey(User,verbose_name='文章作者')
    views = models.PositiveIntegerField(default=0,verbose_name='阅读量')

    #统计阅读量方法
    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    #重写save方法
    def save(self,*args,**kwargs):
        #如果没有填写摘要
        if not self.excerpt:
            #实例化一个markdown类,用于渲染body的文本
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            #strip_tags去掉HTML文本的全部HTML标签
            #从文本摘取前54个字符赋给excerpt
            self.excerpt = strip_tags(md.convert(self.body))[:54]
        #调用父类的save方法将数据保存到数据库中
        super(Post, self).save(*args,**kwargs)
    class Meta:
        ordering = ['-create_time']
        verbose_name = "文章"
        verbose_name_plural = verbose_name

comments/models.py
from django.db import models


from django.utils.six import python_2_unicode_compatible
# Create your models here.


@python_2_unicode_compatible
class Comment(models.Model):
    name = models.CharField(max_length=100,verbose_name='用户名称')
    email = models.EmailField(max_length=255,verbose_name='邮箱')
    url = models.URLField(blank=True,verbose_name='个人网址')
    text = models.TextField(verbose_name='评论内容')
    # 我们给评论创建一个自动的时间
    created_time = models.DateTimeField(auto_now_add=True,verbose_name='评论时间')

    # 与post数据库相连接，这里是多对一的关系 用ForeignKey连接到Post类 、
    # 即一个comment只能在一篇post里有，但是一个post里可以有很多comment
    post =models.ForeignKey('blog.Post')


    def __str__(self):
        return self.text[:20]

    class Meta:
        ordering=['-created_time']

blog/views.py
import markdown
from django.shortcuts import render,HttpResponse,get_object_or_404
from comments.froms import CommentForm
from  django.views.generic import ListView,DetailView
from .models import Post,Category,Tag
from  django.utils.text import slugify
from markdown.extensions.toc import TocExtension
from  django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .paginator import paginator

#类视图
# class IndexView(ListView):
#     model = Post
#     template_name = 'blog/index.html'
#     context_object_name = 'post_list'
#     #开启分页功能
#     paginate_by = 2
#
#     def get_context_data(self, **kwargs):
#         #获取父类生成的传递给模板的字典
#         context = super().get_context_data(**kwargs)
#         paginator = context.get('paginator')
#         page = context.get('page_obj')
#         is_paginated = context.get('is_paginated')
#         # pagination_data = self.pagination_data(paginator,page,is_paginated)
#         pagination_data = self.pagination_data(paginator, page, is_paginated)
#         #将分页导航条的模板变量更新到context中,返回的为字典
#         context.update(pagination_data)
#
#         #将更新后的context返回,以便ListView使用这个字典的模板变量去渲染模板
#         #此时context字典中已有了显示分页导航条所需的数据
#         return context
#
#     def pagination_data(self,paginator,page,is_paginated):
#         if not  is_paginated:
#             #如果没有分页，此时返回一个空字典
#             return {}
#         #当前页左边连续的页码号，初始值为空
#         left = []
#         #当前页码右边连续的页码号，初始值为空
#         right = []
#         #标示第一页页码后是否需要显示省略号
#         left_ha_more = False
#         #标示最后一页页码前是否需要显示省略号
#         right_has_more = False
#         #标示是否需要显示第一页的页码号
#         #初始False
#         first = False
#         #标示是否需要显示最后一页的页码号
#         # 初始False
#         last = False
#
#         #获取用户当前请求的页码号
#         page_number = page.number
#
#         #获取分页后的总页数
#         total_pages = paginator.num_pages
#
#
#         #获取整个分页页码列表，比如分了4页，那么久是[1,2,3,4]
#         page_range = paginator.page_range
#
#         if page_number == 1:
#             right = page_range[page_number:page_number +2]
#
#
#             if right[-1] < total_pages - 1:
#                 right_has_more = True
#                 print(right[-1],total_pages -1 )
#
#
#             if right[-1] < total_pages:
#                 last = True
#         elif page_number == total_pages:
#             left = page_range[(page_number -3) if (page_number -3 ) > 0 else 0:page_number -1]
#
#             if left[0] >2:
#                 left_ha_more = True
#
#             if left[0] > 1:
#                 first =True
#         else:
#             left = page_range[(page_number -3 ) if (page_number -3) >0 else 0:page_number -1 ]
#             right = page_range[page_number:page_number +2]
#
#             if right[-1] < total_pages -1:
#                 right_has_more = True
#
#             if right[-1] < total_pages:
#                 last =True
#
#             if left[0] >2:
#                 left_ha_more = True
#             if left[0] >1:
#                 first = True
#
#         data = {
#             'left':left,
#             'right':right,
#             'left_has_more':left_ha_more,
#             'righr_has_more':right_has_more,
#             'first':first,
#             'last':last,
#         }
#         return  data



#类视图
class PostDetaiIView(DetailView):
    '''文章详情'''
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post_detail'

    def get(self, request, *args, **kwargs):
        response = super(PostDetaiIView,self).get(request,*args,**kwargs)
        # 将文章阅读量 +1
        # 注意 self.object 的值就是被访问的文章 post
        self.object.increase_views()
        # 视图必须返回一个 HttpResponse 对象
        return response

    def get_object(self, queryset=None):
        # 覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染
        post_detail = super(PostDetaiIView,self).get_object(queryset=None)
        # post_detail.body = markdown.markdown(post_detail.body,
        #                                      extensions=[
        #                                          'markdown.extensions.extra',
        #                                          'markdown.extensions.codehilite',
        #                                          'markdown.extensions.toc',
        #                                      ])
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            # 'markdown.extensions.toc',
            TocExtension(slugify=slugify),
        ])
        post_detail.body = md.convert(post_detail.body)
        post_detail.toc = md.toc
        return post_detail

    def get_context_data(self, **kwargs):
        context = super(PostDetaiIView,self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
            'form': form,
            'comment_list': comment_list
        })
        return context


class ArchivesView(ListView):
    '''归档'''
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        return super(ArchivesView,self).get_queryset().filter(create_time__year = self.kwargs.get('year'),create_time__month = self.kwargs.get('month'))


class CategoryView(ListView):
    '''分类'''
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        cate = get_object_or_404(Category,pk=self.kwargs.get('pk'))
        return  super(CategoryView,self).get_queryset().filter(category = cate)


class TagView(ListView):
    '''标签'''
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        tag = get_object_or_404(Tag,pk=self.kwargs.get('pk'))
        return super(TagView,self).get_queryset().filter(tags=tag)


def search(request):
    '''搜索'''
    q = request.GET.get('q')
    error_msg= ''

    if not q:
        error_msg="请输入关键词"
        return  render(request,'blog/index.html',{'error_msg':error_msg})
    post_list = Post.objects.filter(Q(title__icontains=q)|Q(body__icontains=q))
    return render(request,'blog/index.html',{'error_msg':error_msg,
                                             'post_list':post_list})
#函数视图
# Create your views here.
# def index(request):
#     """首页"""
#
#         # 获取Book数据表中的所有记录
#     post_list = Post.objects.all()
#     print(post_list)
#     data = paginator(request,post_list,6)
#     #     # 生成paginator对象,定义每页显示10条记录
#     # paginator = Paginator(post_list, 5)
#     #     # 从前端获取当前的页码数,默认为1
#     # page = request.GET.get('page', 1)
#     #     # 把当前的页码数转换成整数类型
#     # currentPage = int(page)
#     #
#     # try:
#     #     print(page)
#     #     post_list = paginator.page(page)  # 获取当前页码的记录
#     # except PageNotAnInteger:
#     #     post_list = paginator.page(1)  # 如果用户输入的页码不是整数时,显示第1页的内容
#     # except EmptyPage:
#     #     post_list = paginator.page(paginator.num_pages)  # 如果用户输入的页数不在系统的页码列表中时,显示最后一页的内容
#
#     return render(request,'blog/index.html',data)
#     # return render(request,'blog/index.html',context={'post_list':post_list})



# def detail(request,pk):
#     """详情页"""
#     post_detail = get_object_or_404(Post,pk=pk)
#     print(post_detail.body)
#     post_detail.increase_views()
#     post_detail.body = markdown.markdown(post_detail.body,
#                                   extensions=[
#                                       'markdown.extensions.extra',
#                                       'markdown.extensions.codehilite',
#                                       'markdown.extensions.toc',
#                                   ])
#     form = CommentForm()
#     comment_list = post_detail.comment_set.all()
#     context = {
#         'post_detail': post_detail,
#         'form': form,
#         'comment_list': comment_list
#     }
#     return render(request, 'blog/detail.html', context=context)

# def archives(request,year,month):
#     post_list = Post.objects.filter(create_time__year=year,
#                                     create_time__month=month).order_by('-create_time')
#     return  render(request,'blog/index.html',context={"post_list": post_list})

# def category(request,pk):
#     """分类页面"""
#     cate = get_object_or_404(Category,pk=pk)#获取分类ID
#     post_list = Post.objects.filter(category=cate)
#     return render(request,'blog/index.html',context={"post_list":post_list})


def index(request):
    '''文章首页'''
    post_list = Post.objects.all()  #导入的Article模型
    p = Paginator(post_list,5)   #分页，10篇文章一页
    if p.num_pages <= 1:  #如果文章不足一页
        post_list = post_list  #直接返回所有文章
        data = ''  #不需要分页按钮
    else:
        page = int(request.GET.get('page',1))  #获取请求的文章页码，默认为第一页
        post_list = p.page(page) #返回指定页码的页面
        left = []  # 当前页左边连续的页码号，初始值为空
        right = []  # 当前页右边连续的页码号，初始值为空
        left_has_more = False  # 标示第 1 页页码后是否需要显示省略号
        right_has_more = False  # 标示最后一页页码前是否需要显示省略号
        first = False   # 标示是否需要显示第 1 页的页码号。
        # 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
        # 其它情况下第一页的页码是始终需要显示的。
        # 初始值为 False
        last = False  # 标示是否需要显示最后一页的页码号。
        total_pages = p.num_pages
        page_range = p.page_range
        if page == 1:  #如果请求第1页
            right = page_range[page:page+2]  #获取右边连续号码页
            if right[-1] < total_pages - 1:    # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
                # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
                right_has_more = True
            if right[-1] < total_pages:   # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
                # 所以需要显示最后一页的页码号，通过 last 来指示
                last = True
        elif page == total_pages:  #如果请求最后一页
            left = page_range[(page-3) if (page-3) > 0 else 0:page-1]  #获取左边连续号码页
            if left[0] > 2:
                left_has_more = True  #如果最左边的号码比2还要大，说明其与第一页之间还有其他页码，因此需要显示省略号，通过 left_has_more 来指示

templates/blog/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block  main %}
    <!--详情页头部 -->
    <article class="post post-{{ post_detail.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">{{ post_detail.title }}</h1>
            <div class="entry-meta">
                {#        {% for tag in post_detail.tags.all %}#}
                {#            <span style="color: red">{{ tag.name }}</span>#}
                {#        {% endfor %}#}
                <span class="post-category"><a href="#">{{ post_detail.category.name }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="{{ post_detail.create_time }}">{{ post_detail.create_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post_detail.author }}</a></span>
                <span class="comments-link"><a href="#">{{ comment_list|length }} 评论</a></span>
                <span class="views-count"><a href="#">{{ post_detail.views }} 阅读</a></span>
            </div>
        </header>

        <!--详情页文章正文 -->
        <div class="entry-content clearfix ">
            {#    		<div class="head-img img-responsive">#}
            {#    			<br>#}
            {#    			<img class='img-thumbnail' src="{{ post.headimage.url }}" alt='文章配图' width="500" height="300">#}
            {#    		</div>#}
            {#    		<br>#}
            <div class="entry-content clearfix ">
                <div class='jupe' id='needtoc'>
                    {{ post_detail.body|safe }}
                    <div class="widget-tag-cloud">
                        <ul>
                            标签：
                            {% for tag1 in post_detail.tags.all %}
                                <li><a href="{% url 'blog:tag' tag1.pk %}"># {{ tag1.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>

    </article>
    <!--简易评论框
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="{% url 'comments:post_comment' post_detail.pk %}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    <label for="{{ form.name.id_for_label }}">名字：</label>{{ form.name }}{{ form.name.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.email.id_for_label }}">邮箱：</label>{{ form.email }}{{ form.email.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.url.id_for_label }}">网址：</label>{{ form.url }}{{ form.url.errors }}
                </div>
                <div class="col-md-12">
                    <label for="{{ form.text.id_for_label }}">评论：</label>{{ form.text }}{{ form.text.errors }}
                    <button type="submit" class=" btn btn-info">发表</button>
                </div>
                <input type="hidden" name="comment_parent" id="comment_parent" value="0">
            </div>

        </form>

        评论开始
        <div class="comment-list-panel">
            <h3>评论列表，共 <span>{{ comment_list|length }}</span> 条评论</h3>
            <ul class="comment-list list-unstyled">
                {% for commengt in comment_list %}
                    <li class="comment-item">
                        <span class="nickname">{{ commengt.name }}</span>
                        <time class="submit-date" >{{ commengt.created_time }}</time>
                        <div class="text">
                            {{ commengt.text|safe }}
                        </div>
                    </li>
                {% empty %}
                    暂无评论
                {% endfor %}
            </ul>

        </div>
    </section>
    -->

    <!-- 来必力City版安装代码 -->
    <div id="lv-container" data-id="city" data-uid="MTAyMC8zMzY3MS8xMDIyNg==">
        <script type="text/javascript">
            (function(d, s) {
                var j, e = d.getElementsByTagName(s)[0];

                if (typeof LivereTower === 'function') { return; }

                j = d.createElement(s);
                j.src = 'https://cdn-city.livere.com/js/embed.dist.js';
                j.async = true;

                e.parentNode.insertBefore(j, e);
            })(document, 'script');
        </script>
        <noscript> 为正常使用来必力评论功能请激活JavaScript</noscript>
    </div>
    <!-- City版安装代码已完成 -->


{% endblock main %}

templates/blog/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load blog_tags %}

{% block  main %}
        <!-- 文章列表-->
    {% if error_msg %}
        <p>{{ error_msg }}</p>
    {% endif %}
    {% for post in post_list %}
        <article class="post post-{{ post.pk }}">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h1>
                <div class="entry-meta">
                    {#{% for tag in post.tags.all %}#}
                    {#<span style="color: red">{{ tag.name }}</span>#}
                    {#{% endfor %}#}
                    <span class="post-category"><a
                            href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                              datetime="{{ post.create_time }}">{{ post.create_time }}</time></a></span>
                    <span class="post-author"><a href="#">{{ post.author }}</a></span>
                    <span class="comments-link"><a
                            href="{{ post.get_absolute_url }}#comment-area">{{ post.comment_set.all|length }} 评论</a></span>
                    <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">

                {#<p>摘要:{{ post.body|truncatechars:20 }}</p>#}
                <p>摘要:{{ post.excerpt }}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }} " class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}
    <hr/>
           <!-- 文章列表结束-->

    <!-- 分页方式一开始
    <!-- 缺点：文章数量太多，分页长度会很长不美观--》
    <nav id="pc_pagination" class="text-left">
        <div class="container">
            <ul class="pagination" id="pager">
                上一页按钮开始,如果当前页有上一页
                {% if post_list.has_previous %}
                    当前页的上一页按钮正常使用
                    <li class="previous"><a href="/?page={{ post_list.previous_page_number }}">上一页</a></li>
                {% else %}
                    当前页的不存在上一页时,上一页的按钮不可用

                    <li class="previous disabled"><a href="#">上一页</a></li>
                {% endif %}
                上一页按钮结束页码开始
                {% for num in paginator.page_range %}
                    {% if num %}
                        {% if num == currentPage %}
                            <li class="item active"><a href="/?page={{ num }}">{{ num }}</a></li>
                        {% else %}
                            <li class="item"><a href="/?page={{ num }}">{{ num }}</a></li>
                        {% endif %}
                    {% else %}
                        <li><a href="#">...</a></li>
                    {% endif %}
                {% endfor %}
                页码结束下一页按钮开始
                {% if post_list.has_next %}
                    <li class="next"><a href="/?page={{ post_list.next_page_number }}">下一页</a></li>

                {% else %}
                    <li class="next disabled"><a href="#">下一页</a></li>
                {% endif %}
                下一页按钮结束
            </ul>
        </div>
    </nav>
    分页方式一结束 -->

    <!-- 分页方式二开始 -->
        <!-- 优化版-->
    {% if data %}
            <nav id="pc_pagination" class="text-left">
        <div class="container">
            <ul id="pages" class="pagination pagination-sm pagination-xs">
            <li class="previous"><a href="/?page=1">首页</a></li>

                            {% if post_list.has_previous %}
{#                    当前页的上一页按钮正常使用#}
                    <li class="previous"><a href="/?page={{ post_list.previous_page_number }}">上一页</a></li>
                {% else %}
{#                    当前页的不存在上一页时,上一页的按钮不可用#}

                    <li class="previous disabled"><a href="#">上一页</a></li>
                {% endif %}
{#                上一页按钮结束页码开始#}
                            {% if data.first %}
                    <li><a href="?page=1">1</a></li>
                {% endif %}
                {% if data.left %}
                    {% if data.left_has_more %}
                        <li><span>...</span></li>
                    {% endif %}
                    {% for i in data.left %}
                        <li><a href="?page={{i}}">{{i}}</a></li>
                    {% endfor %}
                {% endif %}
                <li class="active"><a href="?page={{data.page}}">{{data.page}}</a></li>
                {% if data.right %}
                    {% for i in data.right %}
                        <li><a href="?page={{i}}">{{i}}</a></li>
                    {% endfor %}
                    {% if data.right_has_more %}
                        <li><span>...</span></li>
                    {% endif %}
                {% endif %}
                {% if data.last %}
                    <li><a href="?page={{data.total_pages}}">{{data.total_pages}}</a></li>
                {% endif %}
{#                            页码结束下一页按钮开始#}
                {% if post_list.has_next %}
                    <li class="next"><a href="/?page={{ post_list.next_page_number }}">下一页</a></li>

                {% else %}
                    <li class="next disabled"><a href="#">下一页</a></li>
                {% endif %}
{#                下一页按钮结束#}
            <li class="next"><a href="/?page={{ data.total_pages }}">尾页</a></li>
            </ul>
        </div>
            </nav>
{% endif %}
    <!-- 分页方式二结束-->

{% endblock main %}